run eval after train
snuailab/waffle_hub pull request #193
Opened 2023-06-20 04:28 UTC by dustjr1565

before
```
hub = Hub.new(...)
hub.train(dataset_path = ....)
# only run train
```

after
```
ds = Dataset.load(...)
hub = Hub.new(...)
hub.train(ds, ...)
# run train than eval
```

2023-06-21 02:10 UTC, ZeroAct approved these changes
Need to fix docstring of dataset in train

2023-06-22 03:47 UTC, dustjr1565 commented
@rmk1075 와플 hub에서 dataset을 받는 형식이 달라집니다. 참고바랍니다

2023-06-23 02:02 UTC, ZeroAct requested changes
.

2023-06-23 23:48 UTC, ZeroAct approved these changes

2023-06-23 23:49 UTC, merged