[Update] Auto labeling
snuailab/waffle_hub pull request #208
Opened 2023-06-30 09:32 UTC by kimdanni

update readme, library

2023-06-30 09:35 UTC, kimdanni commented
@ZeroAct 리뷰어 등록이 안되어 코멘트로 남기겠습니다

2023-07-02 02:02 UTC, ZeroAct approved these changes

2023-07-02 02:05 UTC, ZeroAct requested changes

2023-07-02 02:05 UTC, ZeroAct commented on GroundingDINO
please remove this submodule

2023-07-03 01:33 UTC, merged