[WIP] Semantic Segmentation Porting
snuailab/waffle_hub pull request #288
Opened 2023-10-23 07:21 UTC by dustjr1565

1. Semantic Segmentation Porting in DLT
- metric: mpa (mean pixel accuracy), iou

2. After the training is completed, "artifacts/model.json" will be copied to "configs/model.json" << Please provide feedback on this.

2023-10-30 01:37 UTC, ZeroAct requested changes

2023-10-30 01:37 UTC, ZeroAct commented on tests/test_hub.py
> +    _total(hub, dataset, image_size, tmpdir)
Should remove `pytest.mark.skip`, plz

2023-10-30 04:33 UTC, Jiyong-Jeon commented on waffle_hub/dataset/adapter/autocare_dlt.py
> +    elif self.task == TaskType.SEMANTIC_SEGMENTATION:
NIT: If it's a code that checks if it's a valid task, I think we can reduce the number of codes.

2023-10-30 04:33 UTC, Jiyong-Jeon commented on waffle_hub/hub/adapter/autocare_dlt/autocare_dlt_hub.py
> +
The logic will be modified by Refectoring.

2023-10-30 04:33 UTC, Jiyong-Jeon commented on tests/test_utils.py
>  )
We don't have test codes related to 'evalute_instance_segmentation' and 'evalute_semantic_segmentation', can you add them?

2023-10-31 00:19 UTC, Jiyong-Jeon approved these changes

2023-11-09 03:53 UTC, ZeroAct commented on waffle_hub/hub/model/wrapper.py
> +class SemanticSegmentationResultParset(ResultParser):
`Parset` -> `Parser` 😂

2023-11-09 03:55 UTC, ZeroAct commented on waffle_hub/hub/model/wrapper.py
> +class SemanticSegmentationResultParset(ResultParser):
I'll merge this branch after fixing it.

2023-11-09 04:32 UTC, ZeroAct approved these changes

2023-11-09 04:33 UTC, merged