implement segmentation task in ultralytics hub
snuailab/waffle_hub pull request #76
Opened 2023-04-24 07:30 UTC by dustjr1565

implement segmentation task in ultralytics hub

2023-04-24 08:04 UTC, dustjr1565 commented
I will add the dataset for the test code and submit the pull request again... Sorry for the inconvenience.

2023-04-26 04:04 UTC, echoyunjin approved these changes

2023-05-01 01:19 UTC, ZeroAct requested changes
It seems that the segmentation of ultralytics is instance segmentation... not semantic segmentation.

2023-05-01 01:20 UTC, ZeroAct commented
> It seems that the segmentation of ultralytics is instance segmentation... not semantic segmentation.

I'll fix it.

2023-05-01 06:10 UTC, closed without merging